name: Docker Deployment Workflow

# Define when the workflow triggers
on:
  # Trigger on pushes to main branch
  push:
    branches: [ "main" ]
  
  # Optional: Allow manual triggering
  workflow_dispatch:

# Define environment variables (optional)
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DROPLET_IP: ${{ secrets.DROPLET_IP }}

# Jobs define the workflow steps
jobs:
  build-and-deploy:
    # Runner environment
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ani-web:${{ github.sha }} .
      
      # Push image to Docker Hub
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ani-web:${{ github.sha }}
      
      # Deploy to Digital Ocean Droplet using sshpass for password authentication
      - name: Deploy to Droplet
        env:
          DROPLET_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
        run: |
          # Install sshpass for password authentication
          sudo apt-get update
          sudo apt-get install -y sshpass
          
          # Deploy using sshpass
          sshpass -p "$DROPLET_PASSWORD" ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/ani-web:${{ github.sha }} || { echo 'Docker pull failed'; exit 1; }
            
            # Stop existing container
            docker stop ani-web || true
            docker rm ani-web || true
            
            # Run new container
            docker run -d \
              --name ani-web \
              -p 3000:3000 \
              ${{ secrets.DOCKER_USERNAME }}/ani-web:${{ github.sha }} || { echo 'Docker run failed'; exit 1; }
          "
