name: Docker Deployment Workflow

# Define when the workflow triggers
on:
  # Trigger on pushes to main branch
  push:
    branches: [ "main" ]
  
  # Optional: Allow manual triggering
  workflow_dispatch:

# Define environment variables (optional)
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DROPLET_IP: ${{ secrets.DROPLET_IP }}

# Jobs define the workflow steps
jobs:
  build-and-deploy:
    # Runner environment
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }} .
      
      # Push image to Docker Hub
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }}
      
      # Deploy to Digital Ocean Droplet
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }}
            
            # Stop existing container
            docker stop your-container-name || true
            docker rm your-container-name || true
            
            # Run new container
            docker run -d \
              --name your-container-name \
              -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }}
